-- H7-H10
-- Add snapshot history and richer sync metadata for library synchronization.

create or replace function public.is_valid_library_snapshot_payload(payload jsonb)
returns boolean
language sql
immutable
as $fn$
  select
    jsonb_typeof(payload) = 'object'
    and payload ? 'version'
    and jsonb_typeof(payload -> 'version') = 'number'
    and payload ? 'generatedAt'
    and jsonb_typeof(payload -> 'generatedAt') = 'string'
    and payload ? 'watchlist'
    and jsonb_typeof(payload -> 'watchlist') = 'array'
    and payload ? 'archive'
    and jsonb_typeof(payload -> 'archive') = 'array'
    and payload ? 'watchedState'
    and jsonb_typeof(payload -> 'watchedState') = 'object'
    and payload ? 'userData'
    and jsonb_typeof(payload -> 'userData') = 'object'
    and (
      not payload ? 'syncMeta'
      or (
        jsonb_typeof(payload -> 'syncMeta') = 'object'
        and payload -> 'syncMeta' ? 'deviceId'
        and jsonb_typeof(payload -> 'syncMeta' -> 'deviceId') = 'string'
        and payload -> 'syncMeta' ? 'syncReason'
        and jsonb_typeof(payload -> 'syncMeta' -> 'syncReason') = 'string'
        and payload -> 'syncMeta' ? 'watchlistCount'
        and jsonb_typeof(payload -> 'syncMeta' -> 'watchlistCount') = 'number'
        and payload -> 'syncMeta' ? 'archiveCount'
        and jsonb_typeof(payload -> 'syncMeta' -> 'archiveCount') = 'number'
        and payload -> 'syncMeta' ? 'watchedStateKeyCount'
        and jsonb_typeof(payload -> 'syncMeta' -> 'watchedStateKeyCount') = 'number'
        and payload -> 'syncMeta' ? 'userDataCount'
        and jsonb_typeof(payload -> 'syncMeta' -> 'userDataCount') = 'number'
        and payload -> 'syncMeta' ? 'totalItemCount'
        and jsonb_typeof(payload -> 'syncMeta' -> 'totalItemCount') = 'number'
        and (
          not ((payload -> 'syncMeta') ? 'appVersion')
          or jsonb_typeof(payload -> 'syncMeta' -> 'appVersion') in ('string', 'null')
        )
      )
    )
$fn$;

create table if not exists public.library_snapshot_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  schema_version integer not null,
  payload jsonb not null,
  sync_reason text not null default 'auto',
  device_id text,
  watchlist_count integer not null default 0,
  archive_count integer not null default 0,
  watched_state_key_count integer not null default 0,
  user_data_count integer not null default 0,
  total_item_count integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists library_snapshot_history_user_created_idx
  on public.library_snapshot_history (user_id, created_at desc);

alter table public.library_snapshot_history enable row level security;

drop policy if exists "library_snapshot_history_select_own" on public.library_snapshot_history;
create policy "library_snapshot_history_select_own"
on public.library_snapshot_history
for select
to authenticated
using (auth.uid() = user_id);

revoke all on table public.library_snapshot_history from anon;
revoke all on table public.library_snapshot_history from authenticated;
grant select on table public.library_snapshot_history to authenticated;

drop function if exists public.upsert_library_snapshot(integer, jsonb);

create or replace function public.upsert_library_snapshot(
  p_schema_version integer,
  p_payload jsonb,
  p_sync_reason text default 'auto',
  p_device_id text default null,
  p_watchlist_count integer default 0,
  p_archive_count integer default 0,
  p_watched_state_key_count integer default 0,
  p_user_data_count integer default 0,
  p_total_item_count integer default 0
)
returns public.library_snapshots
language plpgsql
security definer
set search_path = public
as $rpc$
declare
  v_user_id uuid;
  v_result public.library_snapshots;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'Sessão autenticada obrigatória para guardar snapshot.'
      using errcode = '42501';
  end if;

  insert into public.library_snapshots (user_id, schema_version, payload)
  values (v_user_id, p_schema_version, p_payload)
  on conflict (user_id) do update
    set schema_version = excluded.schema_version,
        payload = excluded.payload
  returning * into v_result;

  insert into public.library_snapshot_history (
    user_id,
    schema_version,
    payload,
    sync_reason,
    device_id,
    watchlist_count,
    archive_count,
    watched_state_key_count,
    user_data_count,
    total_item_count
  )
  values (
    v_user_id,
    p_schema_version,
    p_payload,
    coalesce(nullif(trim(p_sync_reason), ''), 'auto'),
    nullif(trim(p_device_id), ''),
    greatest(coalesce(p_watchlist_count, 0), 0),
    greatest(coalesce(p_archive_count, 0), 0),
    greatest(coalesce(p_watched_state_key_count, 0), 0),
    greatest(coalesce(p_user_data_count, 0), 0),
    greatest(coalesce(p_total_item_count, 0), 0)
  );

  return v_result;
end;
$rpc$;

revoke all on function public.upsert_library_snapshot(integer, jsonb, text, text, integer, integer, integer, integer, integer) from public;
grant execute on function public.upsert_library_snapshot(integer, jsonb, text, text, integer, integer, integer, integer, integer) to authenticated;
